package com.bupt.microboot.mapper;

import com.bupt.microboot.entity.EmployeeGenerator;
import com.bupt.microboot.entity.EmployeeGeneratorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    long countByExample(EmployeeGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int insert(EmployeeGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    List<EmployeeGenerator> selectByExample(EmployeeGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    EmployeeGenerator selectByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmployeeGenerator record, @Param("example") EmployeeGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmployeeGenerator record, @Param("example") EmployeeGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeGenerator record);
}