package com.bupt.microboot.mapper;

import com.bupt.microboot.entity.UserGenerator;

public interface UserGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    int insert(UserGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(UserGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    UserGenerator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_t_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGenerator record);
}