# 配置redis
spring:
#  redis:
#    host: 10.237.120.177
#    port: 6380
#    password: c65178899Sc_
#    timeout: 1000
#    database: 0
#    pool:
#      max-active: 10
#      max-idle: 8
#      min-idle: 2
#      max-wait: 100
  redis:
    host: 192.168.0.102
    port: 6379
    password: 100037
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
#  redis:
#    host: 10.237.120.177
#    port: 6379
#    password: c65178899Sc_
#    timeout: 1000
#    database: 0
#    pool:
#      max-active: 10
#      max-idle: 8
#      min-idle: 2
#      max-wait: 100


#  spring.redis.timeout=6000ms
#  spring.redis.database=0
#  spring.redis.cluster.nodes=10.237.120.176:6379,10.237.120.177:6379,10.237.120.178:6379,10.237.120.176:6380,10.237.120.177:6380,10.237.120.178:6380
#  spring.redis.password=c65178899Sc_
#  spring.redis.cluster.max-redirects=3
#  spring.redis.lettuce.pool.max-active=1000
#  spring.redis.lettuce.pool.max-idle=10
#  spring.redis.lettuce.pool.min-idle=5
#  spring.redis.lettuce.pool.max-wait=-1

