package com.bupt.microboot.entity;

import java.io.Serializable;

public class EmployeeGenerator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.eid
     *
     * @mbg.generated
     */
    private Long eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.employee_name
     *
     * @mbg.generated
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_t_sys_employee.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_t_sys_employee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.eid
     *
     * @return the value of mb_t_sys_employee.eid
     *
     * @mbg.generated
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.eid
     *
     * @param eid the value for mb_t_sys_employee.eid
     *
     * @mbg.generated
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.employee_name
     *
     * @return the value of mb_t_sys_employee.employee_name
     *
     * @mbg.generated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.employee_name
     *
     * @param employeeName the value for mb_t_sys_employee.employee_name
     *
     * @mbg.generated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.age
     *
     * @return the value of mb_t_sys_employee.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.age
     *
     * @param age the value for mb_t_sys_employee.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.sex
     *
     * @return the value of mb_t_sys_employee.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.sex
     *
     * @param sex the value for mb_t_sys_employee.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.email
     *
     * @return the value of mb_t_sys_employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.email
     *
     * @param email the value for mb_t_sys_employee.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_t_sys_employee.did
     *
     * @return the value of mb_t_sys_employee.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_t_sys_employee.did
     *
     * @param did the value for mb_t_sys_employee.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}